---
- hosts: all
  become: true
  tasks:
  
  - name: Check if RKE exists
    stat:
      path: /usr/local/bin/rke
    register: stat_result

  - name: Get RKE
    get_url:
      url: https://github.com/rancher/rke/releases/download/v1.2.3/rke_linux-amd64
      dest: /usr/local/bin/rke
      mode: 0755
    when: stat_result.stat.exists == False
      
  - name: Print RKE version
    command: "rke --version"
    register: rke_version
  
  - name: Show RKE installed version
    debug:
      var: rke_version.stdout_lines
